name = "cleaning-schedule"
main = "index.js"
compatibility_date = "2024-09-01"
workers_dev = true

routes = [
  { pattern = "ferkomes.com/894yu3hrjfebncdi7su888ybj4esnc/*", zone_name = "ferkomes.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "cleaning-data-sheet"
database_id = "d43a52bb-6818-4006-83ae-be1367d0d681"

[triggers]
crons = ["0 2 * * *"]
